/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.ControladorNomina;
import entidad.Nomempleado;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author danielha
 */
public class NominaIGU extends javax.swing.JFrame {

    /**
     * Creates new form NominaIGU
     */
    public NominaIGU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        campoIdEmpleado = new javax.swing.JTextField();
        campoNombreEmpleado = new javax.swing.JTextField();
        camposalarioEmpleado = new javax.swing.JTextField();
        botonSueldobruto = new javax.swing.JButton();
        botonSueldoReal = new javax.swing.JButton();
        botonSueldoEmpleados = new javax.swing.JButton();
        botonSumaSueldo = new javax.swing.JButton();
        botonPromedio = new javax.swing.JButton();
        botonIdEmpleado = new javax.swing.JButton();
        botonTotal = new javax.swing.JButton();
        botonMenor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        jLabel3.setText("Salario");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        botonSueldobruto.setText("Sueldo bruto");
        botonSueldobruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSueldobrutoActionPerformed(evt);
            }
        });

        botonSueldoReal.setText("Sueldo Real");
        botonSueldoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSueldoRealActionPerformed(evt);
            }
        });

        botonSueldoEmpleados.setText("Sueldos Empleados");
        botonSueldoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSueldoEmpleadosActionPerformed(evt);
            }
        });

        botonSumaSueldo.setText("Suma Sueldos");
        botonSumaSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaSueldoActionPerformed(evt);
            }
        });

        botonPromedio.setText("Prom sueldos");
        botonPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPromedioActionPerformed(evt);
            }
        });

        botonIdEmpleado.setText("IDEmpleados");
        botonIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdEmpleadoActionPerformed(evt);
            }
        });

        botonTotal.setText("Total");
        botonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTotalActionPerformed(evt);
            }
        });

        botonMenor.setText("Menor ");
        botonMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCrear)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEditar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(camposalarioEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(campoNombreEmpleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoIdEmpleado, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSueldobruto)
                            .addComponent(botonSumaSueldo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSueldoReal)
                                .addGap(18, 18, 18)
                                .addComponent(botonSueldoEmpleados)
                                .addGap(18, 18, 18)
                                .addComponent(botonTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonPromedio)
                                .addGap(28, 28, 28)
                                .addComponent(botonIdEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(botonMenor)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(camposalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrear)
                    .addComponent(botonBorrar)
                    .addComponent(botonEditar)
                    .addComponent(botonMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSueldobruto)
                    .addComponent(botonSueldoReal)
                    .addComponent(botonSueldoEmpleados)
                    .addComponent(botonTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSumaSueldo)
                    .addComponent(botonPromedio)
                    .addComponent(botonIdEmpleado)
                    .addComponent(botonMenor))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        
        //Nomempleado e =new Nomempleado();
        String nombre = campoNombreEmpleado.getText();
        String id = campoIdEmpleado.getText();
        int salario = 0;
        salario=Integer.parseInt(camposalarioEmpleado.getText());
        
        if (nombre.equals("")||id.equals("")||salario==0){
            JOptionPane.showMessageDialog(rootPane, "no se han completado los datos");
        }else{
            Nomempleado e =new Nomempleado(id, nombre, salario);
            //e.setId(id);
            //e.setNombre(nombre);
            //e.setSalario(salario);
            ControladorNomina cn = new ControladorNomina();
            cn.crearEmpleado(e);
            campoIdEmpleado.setText("");
            campoNombreEmpleado.setText("");
            camposalarioEmpleado.setText("");
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        String id = campoIdEmpleado.getText();
        if(id.equals("")){
            JOptionPane.showMessageDialog(rootPane, "no se han completado los datos");
        }else{
            ControladorNomina cn = new ControladorNomina();
            cn.borrarEmpleado(id);
            campoIdEmpleado.setText("");
            campoNombreEmpleado.setText("");
            camposalarioEmpleado.setText("");
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
       String nombre = campoNombreEmpleado.getText();
        String id = campoIdEmpleado.getText();
        int salario = 0;
        salario=Integer.parseInt(camposalarioEmpleado.getText());
        
        if (nombre.equals("")||id.equals("")||salario==0){
            JOptionPane.showMessageDialog(rootPane, "no se han completado los datos");
        }else{
            Nomempleado e =new Nomempleado(id, nombre, salario);
            //e.setId(id);
            //e.setNombre(nombre);
            //e.setSalario(salario);
            ControladorNomina cn = new ControladorNomina();
            cn.editarEmpleado(e);
            campoIdEmpleado.setText("");
            campoNombreEmpleado.setText("");
            camposalarioEmpleado.setText("");
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        String id = campoIdEmpleado.getText();
        ControladorNomina cn = new ControladorNomina();
        Nomempleado e= cn.seleccionarEmpleado(id);
        campoIdEmpleado.setText(e.getId());
        campoNombreEmpleado.setText(e.getNombre());
        camposalarioEmpleado.setText(""+e.getSalario());
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void botonSumaSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaSueldoActionPerformed
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.sumaSueldos());
    }//GEN-LAST:event_botonSumaSueldoActionPerformed

    private void botonSueldobrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSueldobrutoActionPerformed
        String id = campoIdEmpleado.getText();
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.sueldoBruto(id));
    }//GEN-LAST:event_botonSueldobrutoActionPerformed

    private void botonSueldoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSueldoRealActionPerformed
        String id = campoIdEmpleado.getText();
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.sueldoreal(id));
    }//GEN-LAST:event_botonSueldoRealActionPerformed

    private void botonSueldoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSueldoEmpleadosActionPerformed
       Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.sueldosEmpleados());
    }//GEN-LAST:event_botonSueldoEmpleadosActionPerformed

    private void botonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTotalActionPerformed
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.total());
    }//GEN-LAST:event_botonTotalActionPerformed

    private void botonPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPromedioActionPerformed
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.promSueldos());
    }//GEN-LAST:event_botonPromedioActionPerformed

    private void botonIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdEmpleadoActionPerformed
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.IDEmpleados());
    }//GEN-LAST:event_botonIdEmpleadoActionPerformed

    private void botonMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenorActionPerformed
        Reportes r = new Reportes();
        JOptionPane.showMessageDialog(rootPane, "total a pagar ="+r.menorSueldo());
    }//GEN-LAST:event_botonMenorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NominaIGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NominaIGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NominaIGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NominaIGU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NominaIGU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonIdEmpleado;
    private javax.swing.JButton botonMenor;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonPromedio;
    private javax.swing.JButton botonSueldoEmpleados;
    private javax.swing.JButton botonSueldoReal;
    private javax.swing.JButton botonSueldobruto;
    private javax.swing.JButton botonSumaSueldo;
    private javax.swing.JButton botonTotal;
    private javax.swing.JTextField campoIdEmpleado;
    private javax.swing.JTextField campoNombreEmpleado;
    private javax.swing.JTextField camposalarioEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
